"""ivlefile dropbox queued time

Revision ID: 11867b64da03
Revises: 4fbd229dbae6
Create Date: 2013-03-10 03:06:47.029000

"""

# revision identifiers, used by Alembic.
revision = '11867b64da03'
down_revision = '4fbd229dbae6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ivle_file', sa.Column('dropbox_queued', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ivle_file', 'dropbox_queued')
    ### end Alembic commands ###
