"""first

Revision ID: 2046ba892660
Revises: None
Create Date: 2013-02-24 01:37:59.400000

"""

# revision identifiers, used by Alembic.
revision = '2046ba892660'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ivle_file', sa.Column('file_type', sa.String(length=8), nullable=True))
    op.add_column('ivle_file', sa.Column('upload_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ivle_file', 'upload_time')
    op.drop_column('ivle_file', 'file_type')
    ### end Alembic commands ###
