"""More metadata for quotas

Revision ID: 3502940549df
Revises: 4d4ffe9376ad
Create Date: 2013-09-24 17:47:01.108931

"""

# revision identifiers, used by Alembic.
revision = '3502940549df'
down_revision = '4d4ffe9376ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_cache', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('dropbox_quota_checked', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dropbox_quota_checked')
    op.drop_column('file_cache', 'file_size')
    ### end Alembic commands ###
