"""add dropbox valid field to users table

Revision ID: 377b449f1482
Revises: 2e5b55e88528
Create Date: 2014-01-22 17:59:41.556671

"""

# revision identifiers, used by Alembic.
revision = '377b449f1482'
down_revision = '2e5b55e88528'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dropbox_valid', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dropbox_valid')
    ### end Alembic commands ###
