"""restore tables...

Revision ID: 47fee1657308
Revises: None
Create Date: 2013-05-01 21:22:38.482769

"""

# revision identifiers, used by Alembic.
revision = '47fee1657308'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ivle_announcement',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('ivle_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=32), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('announcement_creator', sa.String(length=256), nullable=True),
    sa.Column('announcement_title', sa.String(length=256), nullable=True),
    sa.Column('announcement_body', sa.Text(), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_table('ivle_forum_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ivle_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=32), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('post_creator', sa.String(length=256), nullable=True),
    sa.Column('post_title', sa.String(length=256), nullable=True),
    sa.Column('post_body', sa.Text(), nullable=True),
    sa.Column('parent_heading_id', sa.Integer(), nullable=True),
    sa.Column('parent_thread_id', sa.Integer(), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ivle_forum_heading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=32), nullable=True),
    sa.Column('ivle_forum_id', sa.String(length=36), nullable=True),
    sa.Column('ivle_heading_id', sa.String(length=36), nullable=True),
    sa.Column('forum_title', sa.String(length=200), nullable=True),
    sa.Column('heading_title', sa.String(length=200), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dropbox_jobs',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('http_url', sa.String(length=1024), nullable=True),
    sa.Column('method', sa.String(length=4), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_path', sa.String(length=256), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('status_update', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('ivle_module',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(length=16), nullable=True),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('checked', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('ivle_folder',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ivle_id', sa.String(length=36), nullable=True),
    sa.Column('ivle_parent_id', sa.String(length=36), nullable=True),
    sa.Column('ivle_workbin_id', sa.String(length=36), nullable=True),
    sa.Column('course_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.DateTime(), nullable=True),
    sa.Column('sync', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('folder_id')
    )
    op.create_table('dropbox_store',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=True),
    sa.Column('dropbox_copy_ref', sa.String(length=100), nullable=True),
    sa.Column('dropbox_copy_ref_expiry', sa.Date(), nullable=True),
    sa.Column('source_file_path', sa.String(length=200), nullable=True),
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.Column('source_file_revision', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('ivle_file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ivle_workbin_id', sa.String(length=36), nullable=True),
    sa.Column('ivle_id', sa.String(length=36), nullable=False),
    sa.Column('ivle_folder_id', sa.String(length=36), nullable=True),
    sa.Column('course_code', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_type', sa.String(length=8), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('dropbox_queued', sa.DateTime(), nullable=True),
    sa.Column('dropbox_uploaded_date', sa.DateTime(), nullable=True),
    sa.Column('dropbox_revision', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('checked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ivle_file')
    op.drop_table('dropbox_store')
    op.drop_table('ivle_folder')
    op.drop_table('ivle_module')
    op.drop_table('dropbox_jobs')
    op.drop_table('ivle_forum_heading')
    op.drop_table('ivle_forum_thread')
    op.drop_table('ivle_announcement')
    ### end Alembic commands ###
