"""dropbox quota fields

Revision ID: 4d4ffe9376ad
Revises: 509229b69f0a
Create Date: 2013-09-22 14:15:53.636905

"""

# revision identifiers, used by Alembic.
revision = '4d4ffe9376ad'
down_revision = '509229b69f0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('users', sa.Column('dropbox_data_quota', sa.Integer, nullable=True))
    op.add_column('users', sa.Column('dropbox_data_normal', sa.Integer, nullable=True))
    op.add_column('users', sa.Column('dropbox_data_shared', sa.Integer, nullable=True))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dropbox_data_quota')
    op.drop_column('users', 'dropbox_data_shared')
    op.drop_column('users', 'dropbox_data_normal')
    ### end Alembic commands ###
