"""add retry time

Revision ID: 509229b69f0a
Revises: 54435caf4637
Create Date: 2013-09-22 14:11:42.344271

"""

# revision identifiers, used by Alembic.
revision = '509229b69f0a'
down_revision = '54435caf4637'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropbox_jobs', sa.Column('status_retry', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dropbox_jobs', 'status_retry')
    ### end Alembic commands ###
