"""Add IVLE valid till

Revision ID: 5150d83199e0
Revises: 3502940549df
Create Date: 2013-09-30 16:10:12.174242

"""

# revision identifiers, used by Alembic.
revision = '5150d83199e0'
down_revision = '3502940549df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ivle_valid_till', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ivle_valid_till')
    ### end Alembic commands ###
