"""added file size for file_size

Revision ID: 51738164bc4
Revises: c2868f8a6da
Create Date: 2014-02-21 15:41:20.798942

"""

# revision identifiers, used by Alembic.
revision = '51738164bc4'
down_revision = 'c2868f8a6da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ivle_file', sa.Column('file_size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ivle_file', 'file_size')
    ### end Alembic commands ###
