"""new cache table

Revision ID: 54435caf4637
Revises: 47fee1657308
Create Date: 2013-05-03 01:44:40.167920

"""

# revision identifiers, used by Alembic.
revision = '54435caf4637'
down_revision = '47fee1657308'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_cache',
    sa.Column('cache_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('http_url', sa.String(length=1024), nullable=True),
    sa.Column('method', sa.String(length=4), nullable=True),
    sa.Column('download_user_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('status_update', sa.DateTime(), nullable=True),
    sa.Column('status_started', sa.DateTime(), nullable=True),
    sa.Column('status_completed', sa.DateTime(), nullable=True),
    sa.Column('status_fail', sa.Integer(), nullable=True),
    sa.Column('status_retries', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['download_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cache_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_cache')
    ### end Alembic commands ###
